@startuml
skinparam componentStyle rectangle
skinparam shadowing false
skinparam defaultFontName Courier
skinparam packageStyle rectangle
skinparam rectangleBorderColor #555555
skinparam rectangleBackgroundColor #FAFAFA
skinparam noteBackgroundColor #FCFCFC
skinparam arrowColor #555555
skinparam ArrowThickness 1
skinparam linetype ortho
skinparam roundcorner 8
skinparam padding 8

rectangle "Cliente" as Cliente {
  [InterfaceUtilizador]
  [Stubs]
  [ClienteMiddleware]
  [Demultiplexer]
}

rectangle "Servidor" as Servidor {
  [Server]
  [ClientHandler]
  [RequestDispatcher]
  [Servicos]
  [CacheManager]
  [NotificationManager]
  [Repositorios]
}

database "Disco" as Disco {
  [eventos_dia_*.dat]
  [utilizadores.dat]
}

InterfaceUtilizador --> Stubs : chamadas
Stubs --> ClienteMiddleware : invocar()
ClienteMiddleware --> Demultiplexer : 1 ligacao TCP

ClienteMiddleware --> Server : TCP
Server --> ClientHandler : aceita socket
ClientHandler --> RequestDispatcher : despachar()
RequestDispatcher --> Servicos : regra de negocio
Servicos --> CacheManager : agregacoes
Servicos --> NotificationManager : notificacoes
Servicos --> Repositorios : persistencia
Repositorios --> Disco : ficheiros
CacheManager --> Disco : streaming

note right of ClienteMiddleware
Uma ligacao por cliente
Demultiplexa respostas
end note
@enduml
